# Generated by Django 3.2.16 on 2023-01-20 14:25

from django.db import migrations
import ecommerce.product.models
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=ecommerce.product.models.Category, to='product.category'),
        ),
    ]
